---
- name: Create yaml directory if it does not exist
  ansible.builtin.file:
    path: /etc/yaml_files/
    state: directory
    mode: '0755'

- name: Deploy Kubernetes Deployment
  template:
    src: deployment.yaml.j2
    dest: /etc/yaml_files//deployment.yaml
  register: deployment

- name: Deploy Kubernetes Service
  template:
    src: service.yaml.j2
    dest: /etc/yaml_files/service.yaml
  register: service

- name: Deploy Kubernetes Service
  template:
    src: LB_service.yaml.j2
    dest: /etc/yaml_files/LB_service.yaml
  register: service

- name: Apply Kubernetes Deployment
  command: kubectl apply -f /etc/yaml_files/deployment.yaml
  when: deployment.changed

- name: Apply Kubernetes Service
  command: kubectl apply -f /etc/yaml_files/service.yaml
  when: service.changed

- name: Apply Kubernetes LB Service
  command: kubectl apply -f /etc/yaml_files/LB_service.yaml
  when: service.changed
