---
- name: Cluster preparation
  hosts: k8s_cluster
  gather_facts: true
  become: true
  roles:
    - role: disable_swap
    - role: packages
    - role: install_kube

- name: Setup K8S Master
  hosts: master
  become: true
  roles:
    - role: master
    - role: calico
    - role: metalLB

- name: Setup K8S Workers
  hosts: worker
  become: true
  roles:
    - role: worker
