---
- name: Cluster preparation
  hosts: k8s_cluster
  gather_facts: true
  become: true
  roles:
    - role: disable_swap
    - role: packages
    - role: install_kube

- name: Setup K8S Master
  hosts: master
  become: true
  roles:
    - role: master

- name: Setup Calico
  hosts: master
  roles:
    - role: calico

- name: Setup K8S Workers
  hosts: worker
  become: true
  roles:
    - role: worker

- name: Label nodes as Workers
  hosts: master
  roles:
    - role: label_workers
    - role: metalLB
    - role: kube_scheduler_permissions

- name: Clean Cache
  hosts: all
  become: true
  roles:
    - role: clean_cashe