---
- name: Cluster preparation
  hosts: k8s_cluster
  gather_facts: true
  become: true
  roles:
    - role: preparation

- name: Setup K8S Master
  hosts: server
  become: true
  roles:
    - role: master
    - role: calico

- name: Setup K8S Workers
  hosts: worker
  become: true
  roles:
    - role: worker
