---

- hosts: initial_controller:worker
  name: Download k0s on all nodes
  become: yes
  roles:
    - role: download
      tags: download
    - role: prereq
      tags: prereq

- hosts: initial_controller
  gather_facts: yes
  become: yes
  name: Configure initial k0s control plane node
  roles:
    - role: k0s/initial_controller
      tags: init

# - hosts: controller
#   gather_facts: yes
#   become: yes
#   serial: 1
#   name: Configure k0s control plane nodes
#   roles:
#     - role: k0s/controller
#       tags: server

- hosts: worker
  become: yes
  name: Configure k0s worker nodes
  roles:
    - role: k0s/worker
      tags: worker

- hosts: initial_controller
  gather_facts: yes
  become: yes
  name: Configure metallb on initial controller
  roles:
    - role: metalLB

- name: Label nodes as Workers
  hosts: initial_controller
  roles:
    - role: alias
      tags: alias
    - role: label_workers
      tags: label_workers

- hosts: initial_controller
  gather_facts: yes
  become: yes
  name: Setup kube-scheduler permissions
  roles:
    - role: kube_scheduler_permissions

- name: Clean Cache
  hosts: initial_controller:worker
  become: true
  roles:
    - role: clean_cashe
      tags: clean_cashe