---
# tasks file for worker
- name: Join Cluster
  block:
    - name: Ensure /tmp/k8s directory exists on worker
      file:
        path: /tmp/k8s
        state: directory
        mode: '0755'

    - name: Copy join command from localhost to worker
      copy:
        src: /tmp/k8s/join_command.sh
        dest: /tmp/k8s/join_command.sh
        mode: '0755'

    - name: Ensure correct shebang line
      lineinfile:
        path: /tmp/k8s/join_command.sh
        line: "#!/bin/sh"
        insertafter: BOF

    - name: Execute join command on worker
      command: /tmp/k8s/join_command.sh
      register: worker_output

    - name: Debug Complete Output
      debug:
        var: worker_output

- name: Set Kubelet internal IP to match host IP
  lineinfile:
    path: /etc/systemd/system/kubelet.service.d/10-kubelet.conf
    regexp: '^KUBELET_EXTRA_ARGS='
    line: "KUBELET_EXTRA_ARGS='--node-ip={{ ansible_default_ipv4.address }}'"
    create: yes

- name: Set Kubelet internal IP to match host IP
  lineinfile:
    path: /etc/default/kubelet
    regexp: '^KUBELET_EXTRA_ARGS='
    line: "KUBELET_EXTRA_ARGS='--node-ip={{ ansible_default_ipv4.address }}'"
    create: yes

- name: Reload daemon
  command: sudo systemctl daemon-reload

- name: Restart kubelet
  command: sudo systemctl restart kubelet