---
- name: Copy join command from Ansiblehost to the worker nodes.
  become: yes
  copy:
    src: /etc/kubernetes/kubeadm-join.command
    dest: /tmp/kubernetes_join_command
    mode: 0777

- name: Join the Worker node to the cluster (vanilla).
  become: yes
  command: sh /tmp/kubernetes_join_command
  register: join_output

- name: Show the output of cluster join task
  debug: var=join_output
