---
# tasks file for packages
- name: Create param files
  block:
  - name: create an empty file for the Containerd module
    copy:
      content: ""
      dest: /etc/modules-load.d/containerd.conf
      force: no

  - name: configure modules for Containerd
    blockinfile:
      path: /etc/modules-load.d/containerd.conf
      block: |
            overlay
            br_netfilter

  - name: create an empty file for Kubernetes sysctl params
    copy:
      content: ""
      dest: /etc/sysctl.d/99-kubernetes-cri.conf
      force: no

  - name: configure sysctl params for Kubernetes
    lineinfile:
      path: /etc/sysctl.d/99-kubernetes-cri.conf
      line: "{{ item }}"
    with_items:
      - 'net.bridge.bridge-nf-call-iptables  = 1'
      - 'net.ipv4.ip_forward                 = 1'
      - 'net.bridge.bridge-nf-call-ip6tables = 1'

  - name: configure /etc/ufw/sysctl.conf
    lineinfile:
      path: /etc/ufw/sysctl.conf
      line: "{{ item }}"
    with_items:
      - 'net/bridge/bridge-nf-call-ip6tables = 1'
      - 'net/bridge/bridge-nf-call-iptables = 1'
      - 'net/bridge/bridge-nf-call-arptables = 1'

  - name: apply sysctl params without reboot
    command: sysctl --system

- name: Add an apt signing key for Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add apt repository for stable version
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Install packages that allow apt to be used over HTTPS
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - gpg
    - socat

- name: Install docker and its dependecies
  apt: 
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - docker-ce 
    - docker-ce-cli 
    # - containerd.io
  notify:
    - docker status

- name: install containerd (latest version)
  shell: |
          # from here https://www.linuxtechi.com/install-kubernetes-on-ubuntu-22-04/
          sudo apt -y update
          sudo apt install -y containerd.io
          sudo containerd config default | sudo tee /etc/containerd/config.toml >/dev/null 2>&1
          sudo sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml
          sudo systemctl restart containerd


- name: reload daemon
  become: yes
  command: systemctl daemon-reload

- name: enable containerd
  become: yes
  command: systemctl enable --now containerd
  
- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    group: docker