---
# tasks file for label_workers
- name: Assign label to worker nodes
  command: microk8s kubectl label node {{ worker_node_name }} node-role.kubernetes.io/worker=
  loop: "{{ groups['agent'] }}"
  vars:
    worker_node_name: "{{ hostvars[item].inventory_hostname }}"
  become: yes

- name: Assign label to master node
  command: microk8s kubectl label node master node-role.kubernetes.io/master=
  become: yes
