---
- name: Install microk8s
  hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - role: install_microk8s

- name: Configure groups
  hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - role: configure_user_group

- name: Configure master
  hosts: server
  become: true
  roles:
    - role: master

- name: Setup metalLB
  hosts: server
  become: true
  roles:
    - role: metalLB

- name: Configure workers
  hosts: agent
  become: true
  roles:
    - role: workers