---

- name: Make dir for k0s distro(s)
  delegate_to: localhost
  become: false
  file:
    path: distros
    state: directory
  register: distros_path

- name: Download k0s binary k0s-{{ k0s_version }}-amd64
  delegate_to: localhost
  become: false
  get_url:
    url: https://github.com/k0sproject/k0s/releases/download/{{ k0s_version }}/k0s-{{ k0s_version }}-amd64
    dest: "{{ distros_path.path }}"
  # workaround for bug in get_url, https://github.com/ansible/ansible/issues/64016 . Valid for Ansible 2.9, leads to
  # file re-download at every run

- name: Upload k0s binary to amd64 nodes
  copy:
    src: "{{ distros_path.path }}/k0s-{{ k0s_version }}-amd64"
    dest: "{{ k0s_binary_dest }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
