---
- name: Cluster preparation
  hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - role: preparation

- name: Setup K3S Master
  hosts: server
  become: true
  roles:
    - role: master
    - role: calico

- name: Setup K3S Workers
  hosts: agent
  become: true
  roles:
    - role: worker

- name: Label nodes as Workers
  hosts: server
  roles:
    - { role: label_workers, tags: 'label' }
