---
- name: Ensure the /etc/kubernetes directory exists
  file:
    path: /etc/kubernetes
    state: directory
    mode: '0755'

- name: Copy kubeadm-config.yaml template to /etc/kubernetes
  template:
    src: kubeadm-config.yaml.j2
    dest: /etc/kubernetes/kubeadm-config.yaml
    mode: '0644'

- name: Init cluster
  command: kubeadm init --pod-network-cidr={{ cluster_cidr }} --service-cidr={{ service_cidr }} --node-name k8s-control

- name: Generate and store Kubernetes join command
  block:
    - name: Generate join token
      shell: kubeadm token create --print-join-command
      register: kubeadm_join_cmd

    - name: Set join command as a fact
      set_fact:
        kubeadm_join: "{{ kubeadm_join_cmd.stdout }}"

    - name: Show join command
      debug: var=kubeadm_join

    - name: Ensure the directory for kubeadm join command exists
      file:
        path: /etc/kubernetes
        state: directory
        mode: '0755'

    - name: Store join command
      copy:
        content: "{{ kubeadm_join }}"
        dest: /etc/kubernetes/kubeadm-join.command
        mode: '0644'

    - name: Fetch join command from master to control
      fetch:
        src: /etc/kubernetes/kubeadm-join.command
        dest: /etc/kubernetes/kubeadm-join.command
        flat: yes


# - name: Setup MEtallb
#   block:
#   - name: Apply default Metallb naemspace
#     ansible.builtin.command: kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.14.4/config/manifests/metallb-native.yaml
#   - name: Copy configmap
#     ansible.builtin.template:
#       src: "metallb_configmap.yaml.j2"
#       dest: "{{ systemd_dir }}/metallb_configmap.yaml"
#       owner: root
#       group: root
#       mode: 0644
#   - name: Copy service
#     ansible.builtin.template:
#       src: "metallb_service.yaml.j2"
#       dest: "{{ systemd_dir }}/metallb_service.yaml"
#       owner: root
#       group: root
#       mode: 0644
#   - name: Apply configmap
#     ansible.builtin.command: kubectl apply -f {{ systemd_dir }}/metallb_configmap.yaml
#   - name: Apply service
#     ansible.builtin.command: kubectl apply -f {{ systemd_dir }}/metallb_service.yaml